# if gitlab action running occur a error such as 'No toolchains found in the NDK toolchains folder
# for ABI with prefix: mips64el-linux-android', might you need to change 'distributionUrl' of gradle zip and 'classpath'.

name: Check & Build 

on:
  [push, pull_request]
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
        reporter: 'github-pr-check'
        tool_name: 'testtool'

    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build Debug APK
      run: ./gradlew assembleDebug
#    - name: Releasing using Hub
#      uses: ShaunLWM/action-release-debugapk@master  # this value is not any user,it is a pedestal,
#      env:
#       GITHUB_TOKEN: ${{ secrets.TOKEN }}
#       APP_FOLDER: app
#       RELEASE_TITLE: New Build

